# Generated by Django 6.0.2 on 2026-02-15 12:06

import pictures.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accountapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="avatar",
            field=pictures.models.PictureField(
                aspect_ratios=[None, "1/1", "3/2", "16/9"],
                blank=True,
                breakpoints={"l": 1200, "m": 992, "s": 768, "xl": 1400, "xs": 576},
                container_width=1200,
                file_types=["AVIF"],
                grid_columns=12,
                height_field="picture_height",
                null=True,
                pixel_densities=[1, 2],
                upload_to="avatars",
                width_field="picture_width",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="picture_height",
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="picture_width",
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
    ]
