# Generated by Django 6.0.2 on 2026-02-15 11:31

import django.db.models.deletion
import pictures.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("title", models.CharField(max_length=160)),
                ("slug", models.SlugField(max_length=180, unique=True)),
                ("short_description", models.CharField(blank=True, max_length=255)),
                (
                    "cover_image",
                    pictures.models.PictureField(
                        aspect_ratios=[None, "1/1", "3/2", "16/9"],
                        breakpoints={
                            "l": 1200,
                            "m": 992,
                            "s": 768,
                            "xl": 1400,
                            "xs": 576,
                        },
                        container_width=1200,
                        file_types=["AVIF"],
                        grid_columns=12,
                        height_field="picture_height",
                        pixel_densities=[1, 2],
                        upload_to="course_covers",
                        width_field="picture_width",
                    ),
                ),
                ("picture_width", models.PositiveIntegerField(editable=False)),
                ("picture_height", models.PositiveIntegerField(editable=False)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="GradeLevel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("name", models.CharField(max_length=60, unique=True)),
                ("order", models.PositiveIntegerField(db_index=True, default=0)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Subject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("name", models.CharField(max_length=80, unique=True)),
                ("slug", models.SlugField(max_length=120, unique=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Module",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("title", models.CharField(max_length=160)),
                ("order", models.PositiveIntegerField(db_index=True, default=0)),
                ("is_sequential", models.BooleanField(default=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="modules",
                        to="contentapp.course",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Lesson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("title", models.CharField(max_length=180)),
                ("order", models.PositiveIntegerField(db_index=True, default=0)),
                (
                    "lesson_type",
                    models.CharField(
                        default="standard",
                        help_text="e.g. standard, story, practice, revision",
                        max_length=30,
                    ),
                ),
                ("is_published", models.BooleanField(db_index=True, default=False)),
                (
                    "module",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lessons",
                        to="contentapp.module",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CoursePlacement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("order", models.PositiveIntegerField(db_index=True, default=0)),
                ("is_published", models.BooleanField(db_index=True, default=False)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="placements",
                        to="contentapp.course",
                    ),
                ),
                (
                    "grade",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="course_placements",
                        to="contentapp.gradelevel",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="course_placements",
                        to="contentapp.subject",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ContentBlock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "block_type",
                    models.CharField(
                        choices=[
                            ("video", "Video"),
                            ("animation", "Animation"),
                            ("text", "Text"),
                            ("quiz", "Quiz"),
                            ("visual", "Visual Explanation"),
                            ("file", "File/Worksheet"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("order", models.PositiveIntegerField(db_index=True, default=0)),
                ("title", models.CharField(blank=True, max_length=180)),
                ("data", models.JSONField(blank=True, default=dict)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="content_blocks",
                        to="contentapp.lesson",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["lesson", "is_active", "order"],
                        name="contentapp__lesson__3c709a_idx",
                    ),
                    models.Index(
                        fields=["block_type"], name="contentapp__block_t_398c24_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("lesson", "order"), name="uniq_block_order_per_lesson"
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="module",
            index=models.Index(
                fields=["course", "order"], name="contentapp__course__b1e65e_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="module",
            constraint=models.UniqueConstraint(
                fields=("course", "order"), name="uniq_module_order_per_course"
            ),
        ),
        migrations.AddIndex(
            model_name="lesson",
            index=models.Index(
                fields=["module", "is_published", "order"],
                name="contentapp__module__ad8b20_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="lesson",
            constraint=models.UniqueConstraint(
                fields=("module", "order"), name="uniq_lesson_order_per_module"
            ),
        ),
        migrations.AddIndex(
            model_name="courseplacement",
            index=models.Index(
                fields=["grade", "subject", "is_published", "order"],
                name="contentapp__grade_i_68d868_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="courseplacement",
            index=models.Index(
                fields=["course"], name="contentapp__course__13f206_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="courseplacement",
            constraint=models.UniqueConstraint(
                fields=("grade", "subject", "course"), name="uniq_course_placement"
            ),
        ),
        migrations.AddConstraint(
            model_name="courseplacement",
            constraint=models.UniqueConstraint(
                fields=("grade", "subject", "order"),
                name="uniq_course_order_per_grade_subject",
            ),
        ),
    ]
