# Generated by Django 6.0.2 on 2026-02-15 11:28

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GuardianRelationship",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("active", "Active"),
                            ("rejected", "Rejected"),
                            ("revoked", "Revoked"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "requested_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("responded_at", models.DateTimeField(blank=True, null=True)),
                ("can_view_progress", models.BooleanField(default=True)),
                ("can_receive_reports", models.BooleanField(default=True)),
                ("can_view_assessments", models.BooleanField(default=True)),
                ("relation_label", models.CharField(blank=True, max_length=40)),
                (
                    "parent",
                    models.ForeignKey(
                        help_text="User with parent role",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="child_links",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="guardian_requests_made",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        help_text="User with student role",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="guardian_links",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["parent", "status"],
                        name="relationshi_parent__b2f8b4_idx",
                    ),
                    models.Index(
                        fields=["student", "status"],
                        name="relationshi_student_cccaf4_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("parent", "student"), name="uniq_parent_student_link"
                    )
                ],
            },
        ),
    ]
